FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster-arm32v7 AS build
WORKDIR /system
COPY . .
RUN dotnet publish -c Release -r linux-arm -o bin/publish /p:LinkDuringPublish=true

FROM mcr.microsoft.com/dotnet/core/runtime-deps:3.0-buster-slim-arm32v7 AS runtime
LABEL Author="Vadim Kosin <vkosin@outlook.com>"
WORKDIR /system
COPY --from=build /system/ThinkingHome.Console/bin/publish .

CMD ["./ThinkingHome.Console"]