#FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster-arm32v7 AS build
FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS build
WORKDIR /system
COPY . .
RUN dotnet publish -c Release -o bin/publish /p:LinkDuringPublish=true

FROM mcr.microsoft.com/dotnet/core/runtime:3.0-buster-slim-arm32v7 AS runtime

LABEL Author="Vadim Kosin <vkosin@outlook.com>"
WORKDIR /system
COPY --from=build /system/bin/publish .

EXPOSE 8080

CMD ["./ThinkingHome.Console"]